### ISSUE TITLE
Provide data in card for rendering in web-app dialogs

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm-pack-lifecycle#10]
Issue moved from atomist/card-automation#7

Created by @jrday at 2019-06-26T01:19:25Z:

The dialogs in web-app should get the same data as chat for consistency. 

A Slack cancel goals dialog:

<img width="526" alt="Screen Shot 2019-06-25 at 15 39 22" src="https://user-images.githubusercontent.com/774714/60143857-1624f780-9775-11e9-874a-ced7bda24e13.png">

A similar dialog in web-app:

<img width="1596" alt="Screen Shot 2019-06-25 at 18 17 30" src="https://user-images.githubusercontent.com/774714/60143984-a8c59680-9775-11e9-893c-7b807254c249.png">

@drewmca has details on the differing payloads – the card pushed is not getting the same data as the chat message.

**Comment by cdupuis** [comment]
Yes, we never designed the card actions to have confirmation information. Adding this now.

**Comment by cdupuis** [comment]
The card action will now have the following additional properties if a confirmation is requested:

```

confirm: {
  title: string,
  body: string,
  ok?: string,
  dismiss?: string,
}

```

**Comment by drewmca** [comment]
@jrday

**Comment by drewmca** [comment]
@cdupuis is this additional data in staging yet? I'm not seeing it come across for a card with a "Cancel" button.

**Comment by cdupuis** [comment]
Yes, this is even in prod. And I have confirmed that it works fine. I see the above on cards.

**Comment by drewmca** [comment]
@cdupuis I'm not seeing it. I thought it might be because I was looking at old cards, so i created a new project with goalsets. The goalset has a cancel action, and the data looks like this:

```
{
  "text": "Cancel",
  "type": "button",
  "registration": "@atomist/lifecycle-automation",
  "command": "CancelGoalSets",
  "parameters": [
    {
      "name": "goalSetId",
      "value": "5d3fb4e9-8059-4d87-94e0-e19f8bfab977"
    }
  ],
  "parameterName": null,
  "parameterOptions": [],
  "parameterOptionGroups": [],
  "role": null
}
```

**Comment by drewmca** [comment]
Maybe the difference is that this is an action contained within a goalset?

**Comment by cdupuis** [comment]
Are you including the `confirm` property in your query? From the result I suspect not.

**Comment by drewmca** [comment]
doh...
