### ISSUE TITLE
Bot should not suggest `enroll org` when joining channel

### ISSUE THREAD

**Issue by kipz** [atomist/sdm-pack-lifecycle#16]
Issue moved from atomisthq/bot-service#1111

Created by @kipz at 2019-08-07T12:15:19Z:

---
Comment by @kipz at 2019-08-07T12:16:01Z:

![Screenshot_20190807_130614](https://user-images.githubusercontent.com/1865026/62622105-7d59ce00-b915-11e9-9687-89765dc89ca8.png)

---
Comment by @slimslenderslacks at 2019-08-07T16:06:55Z:

we'll probably never find the message but let's at least give it a try.

---
Comment by @neilprosser at 2019-08-07T16:14:51Z:

Got it! https://github.com/atomist/sdm-pack-lifecycle/blob/f78604f3b19a320b7a9a5735268c5a99af55de8c/lib/handlers/event/channellink/BotJoinedChannel.ts#L104

**Comment by cdupuis** [comment]
:-)

**Comment by kipz** [comment]
Happy to take this if/when it reaches the top!

**Comment by kipz** [comment]
Current thinking is to replace it with instructions to visit the web-app to link an org/installation.
